spring:
    profiles:
        active: dev
    applicaiton:
        name: wx-athena
    thymeleaf:
        cache: false
    http:
        multipart:
            maxFileSize: 50Mb
            maxRequestSize: 50Mb

server:
    port: 9999
    tomcat:
        basedir: tomcat
        accesslog:
            enabled: true
            directory: logs
            pattern: "%{X-Forwarded-For}i %{userToken}i - %h %l %u %t \"%r\" %s %b %D %F %T"
            rotate: true
            buffered: true
            rename-on-rotate: true
            prefix: localhost_access_log
            suffix: .txt

mybatis:
    typeAliasesPackage: com.yiyuankafei.wx.athena.entity
    mapper-locations: classpath:com/yiyuankafei/wx/athena/mapper/*Mapper.xml

