spring:
  datasource:
    min-idle: 3
    max-active: 20
    time-between-eviction-runs-millis: 60000
    test-while-idle: true
    poolPreparedStatements: true
    type: com.alibaba.druid.pool.DruidDataSource
    max-wait: 60000
    url: jdbc:mysql://47.92.209.37:3306/emoticon?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false&serverTimezone=Asia/Shanghai
    test-on-borrow: false
    password: yiyuankafei
    min-evictable-idle-time-millis: 300000
    initial-size: 1
    driver-class-name: com.mysql.jdbc.Driver
    test-on-return: false
    username: root

mybatis:
  mapper-locations: classpath:com/yiyuankafei/wx/athena/mapper/*.xml,classpath:com/yiyuankafei/wx/athena/mapper/custom/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl